version: '3.8'

services:
  # MongoDB container
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your-mongo-username
      MONGO_INITDB_ROOT_PASSWORD: your-mongo-password
    volumes:
      - mongodb-data:/data/db

  # Java REST API container
  java-api:
    build:
      context: .
      dockerfile: ./task/Dockerfile
    container_name: java-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/vendingMachine
    networks:
      - backend

networks:
  backend:


volumes:
  mongodb-data:
